<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="7" passed="2" failed="5" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-05-24T15:46:07 IST" name="Default suite" finished-at="2022-05-24T15:47:02 IST" duration-ms="55532">
    <groups>
    </groups>
    <test started-at="2022-05-24T15:46:07 IST" name="Default test" finished-at="2022-05-24T15:47:02 IST" duration-ms="55532">
      <class name="testcases.TC001_LoginTest">
        <test-method is-config="true" signature="launchUrl(java.lang.String)[pri:0, instance:testcases.TC001_LoginTest@4e096385]" started-at="2022-05-24T15:46:07 IST" name="launchUrl" finished-at="2022-05-24T15:46:19 IST" duration-ms="12407" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchUrl -->
        <test-method signature="TC001_Login()[pri:0, instance:testcases.TC001_LoginTest@4e096385]" started-at="2022-05-24T15:46:19 IST" name="TC001_Login" finished-at="2022-05-24T15:46:26 IST" duration-ms="6687" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC001_Login -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testcases.TC001_LoginTest@4e096385]" started-at="2022-05-24T15:46:26 IST" name="tearDown" finished-at="2022-05-24T15:46:26 IST" duration-ms="464" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testcases.TC001_LoginTest -->
      <class name="testcases.TC002_DDT_LoginTest">
        <test-method is-config="true" signature="launchUrl(java.lang.String)[pri:0, instance:testcases.TC002_DDT_LoginTest@649bec2e]" started-at="2022-05-24T15:46:07 IST" name="launchUrl" finished-at="2022-05-24T15:46:19 IST" duration-ms="12310" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchUrl -->
        <test-method signature="DDTLoginTest(java.lang.String, java.lang.String)[pri:0, instance:testcases.TC002_DDT_LoginTest@649bec2e]" started-at="2022-05-24T15:46:21 IST" name="DDTLoginTest" data-provider="DataWithLogin" finished-at="2022-05-24T15:46:31 IST" duration-ms="9704" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[mngr409557]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[hyqYtep]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DDTLoginTest -->
        <test-method signature="DDTLoginTest(java.lang.String, java.lang.String)[pri:0, instance:testcases.TC002_DDT_LoginTest@649bec2e]" started-at="2022-05-24T15:46:31 IST" name="DDTLoginTest" data-provider="DataWithLogin" finished-at="2022-05-24T15:46:38 IST" duration-ms="6450" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Hadi]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Heena]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertTrue(Assert.java:52)
at testcases.TC002_DDT_LoginTest.DDTLoginTest(TC002_DDT_LoginTest.java:28)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DDTLoginTest -->
        <test-method signature="DDTLoginTest(java.lang.String, java.lang.String)[pri:0, instance:testcases.TC002_DDT_LoginTest@649bec2e]" started-at="2022-05-24T15:46:38 IST" name="DDTLoginTest" data-provider="DataWithLogin" finished-at="2022-05-24T15:46:44 IST" duration-ms="6547" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Baba]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Ammi]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertTrue(Assert.java:52)
at testcases.TC002_DDT_LoginTest.DDTLoginTest(TC002_DDT_LoginTest.java:28)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DDTLoginTest -->
        <test-method signature="DDTLoginTest(java.lang.String, java.lang.String)[pri:0, instance:testcases.TC002_DDT_LoginTest@649bec2e]" started-at="2022-05-24T15:46:44 IST" name="DDTLoginTest" data-provider="DataWithLogin" finished-at="2022-05-24T15:46:50 IST" duration-ms="5640" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Ayesha]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Nuha]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertTrue(Assert.java:52)
at testcases.TC002_DDT_LoginTest.DDTLoginTest(TC002_DDT_LoginTest.java:28)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DDTLoginTest -->
        <test-method signature="DDTLoginTest(java.lang.String, java.lang.String)[pri:0, instance:testcases.TC002_DDT_LoginTest@649bec2e]" started-at="2022-05-24T15:46:50 IST" name="DDTLoginTest" data-provider="DataWithLogin" finished-at="2022-05-24T15:46:56 IST" duration-ms="6470" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Atiya]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[hannan]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertTrue(Assert.java:52)
at testcases.TC002_DDT_LoginTest.DDTLoginTest(TC002_DDT_LoginTest.java:28)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DDTLoginTest -->
        <test-method signature="DDTLoginTest(java.lang.String, java.lang.String)[pri:0, instance:testcases.TC002_DDT_LoginTest@649bec2e]" started-at="2022-05-24T15:46:56 IST" name="DDTLoginTest" data-provider="DataWithLogin" finished-at="2022-05-24T15:47:02 IST" duration-ms="5680" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Hakeem]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Mehar]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertTrue(Assert.java:52)
at testcases.TC002_DDT_LoginTest.DDTLoginTest(TC002_DDT_LoginTest.java:28)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DDTLoginTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testcases.TC002_DDT_LoginTest@649bec2e]" started-at="2022-05-24T15:47:02 IST" name="tearDown" finished-at="2022-05-24T15:47:02 IST" duration-ms="186" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testcases.TC002_DDT_LoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
